name: Test Action

on:
  workflow_dispatch:
    inputs:
      input_string:
        description: "write some string"
        required: true
        type: string

jobs:
  test_job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Print Input String
        run: echo "You entered:${{ inputs.input_string }}"

      - name: Convert to Uppercase and Output
      
        run: |
          INPUT="${{ inputs.input_string }}"
          OUTPUT=$(echo $INPUT | tr '[:lower:]' '[:upper:]')
          echo "Converted to uppercase: $OUTPUT"
          echo "result=$OUTPUT" >> $GITHUB_OUTPUT
          
      - name: Check Result
        run: echo "The final result is:${{ steps.test_job1.outputs.result }}"






      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Create stg branch"
        id: new-branch
        run: |
          git checkout -b "stg/action-test"

      - name: "Build Changelog"
        id: changelog_builder
        uses: mikepenz/release-changelog-builder-action@v3.7.2
        with:
          fromTag: 952ce4a04b9f919655a0fc39de5bb797cd897b6b
          toTag: dd060c7f9bc489771357275fea2bf22cdb92c579
          configuration: ".github/staging_changelog_configs.json"
          outputFile: "changelog.txt"

      - name: Commit files
        run: |
          echo "開始跑 Commit files"
          if [ ! -z "$(git status --porcelain)" ]; then 
            echo "暫存不為空，加入檔案"
            git config user.email "you@example.com"
            git config user.name "Your Name"
            git add .
            git commit -m "Update changelog"            
          fi
